[
  {
    "__v": 0,
    "_id": "548ce7fa56558e880f60f28d",
    "industry": "media",
    "ivy": "false",
    "risklevel": "10",
    "role": "c_level",
    "sentto": "team",
    "tone": "3",
    "wr_style": "concise"
  },
  {
    "__v": 0,
    "_id": "548db8e956558e880f60f294",
    "industry": "retail",
    "ivy": "true",
    "risklevel": "10",
    "role": "c_level",
    "sentto": "team",
    "tone": "3",
    "wr_style": "concise"
  },
  {
    "__v": 0,
    "_id": "548dc2433603a490243ca834",
    "industry": "media",
    "ivy": "false",
    "risklevel": "10",
    "role": "c_level",
    "sentto": "team",
    "tone": "3",
    "wr_style": "concise"
  },
  {
    "_id": "549d98d05c1dc8f801000000",
    "role": "sr-mgmt",
    "ivy": "true",
    "wr_style": "concise",
    "industry": "finance",
    "risklevel": "10",
    "sentto": "team",
    "tone": "3"
  },
  {
    "_id": "549dc67cff4c90b96ab0ff4c",
    "ivy": "false",
    "risklevel": "10",
    "role": "c_level",
    "tone": "3"
  },
  {
    "tone": "3",
    "sentto": "higher",
    "risklevel": "10",
    "industry": "retail",
    "wr_style": "verbose",
    "ivy": "false",
    "role": "vp",
    "_id": "54a2e721e3e9da7814301ec9",
    "__v": 0
  },
  {
    "_id": "54695fbb5c1dc8f004000001",
    "tone": "3",
    "sentto": "team",
    "risklevel": "2",
    "industry": "finance",
    "wr_style": "simple",
    "ivy": "true",
    "role": "mid_mgmt"
  },
  {
    "role": "mid_mgmt",
    "ivy": "false",
    "wr_style": "simple",
    "industry": "healthcare",
    "risklevel": "5",
    "sentto": "peer",
    "tone": "3",
    "_id": "54695f283d69cc501f7bdd8d",
    "__v": 0
  },
  {
    "role": "c_level",
    "ivy": "true",
    "wr_style": "concise",
    "industry": "finance",
    "risklevel": "7",
    "sentto": "team",
    "tone": "3",
    "_id": "54695f283d69cc501f7bdd7b",
    "__v": 0
  },
  {
    "tone": "3",
    "sentto": "team",
    "risklevel": "7",
    "industry": "media",
    "wr_style": "concise",
    "ivy": "true",
    "role": "c_level",
    "_id": "54711648da073db403ce9286",
    "__v": 0
  },
  {
    "tone": "3",
    "sentto": "team",
    "risklevel": "7",
    "industry": "media",
    "wr_style": "concise",
    "ivy": "true",
    "role": "c_level",
    "_id": "54711779da073db403ce9287",
    "__v": 0
  },
  {
    "tone": "3",
    "sentto": "peer",
    "risklevel": "7",
    "industry": "airlines",
    "wr_style": "concise",
    "ivy": "false",
    "role": "vp",
    "_id": "5478ee8287334f041b7d2089",
    "__v": 0
  },
  {
    "tone": "3",
    "sentto": "team",
    "risklevel": "7",
    "industry": "media",
    "wr_style": "concise",
    "ivy": "true",
    "role": "c_level",
    "_id": "548dd3063603a490243ca846",
    "__v": 0
  },
  {
    "tone": "3",
    "sentto": "peer",
    "risklevel": "7",
    "industry": "internet",
    "wr_style": "concise",
    "ivy": "false",
    "role": "c_level",
    "_id": "549dc712afbbfa3c1252868f",
    "__v": 0
  },
  {
    "tone": "3",
    "sentto": "team",
    "risklevel": "7",
    "industry": "retail",
    "wr_style": "concise",
    "ivy": "true",
    "role": "c_level",
    "_id": "54bb04e9df1b6c901c83fac2",
    "__v": 0
  },
  {
    "role": "sr-mgmt",
    "ivy": "false",
    "wr_style": "verbose",
    "industry": "finance",
    "risklevel": "8",
    "sentto": "team",
    "tone": "3",
    "_id": "54695f283d69cc501f7bdd7d",
    "__v": 0
  },
  {
    "role": "sr-mgmt",
    "ivy": "true",
    "wr_style": "verbose",
    "industry": "finance",
    "risklevel": "8",
    "sentto": "team",
    "tone": "3",
    "_id": "54695f283d69cc501f7bdd7f",
    "__v": 0
  },
  {
    "role": "mid_mgmt",
    "ivy": "true",
    "wr_style": "concise",
    "industry": "healthcare",
    "risklevel": "8",
    "sentto": "team",
    "tone": "3",
    "_id": "54695f283d69cc501f7bdd80",
    "__v": 0
  },
  {
    "role": "sr-mgmt",
    "ivy": "true",
    "wr_style": "verbose",
    "industry": "finance",
    "risklevel": "8",
    "sentto": "team",
    "tone": "3",
    "_id": "54695f283d69cc501f7bdd82",
    "__v": 0
  },
  {
    "role": "sr-mgmt",
    "ivy": "false",
    "wr_style": "concise",
    "industry": "finance",
    "risklevel": "8",
    "sentto": "higher",
    "tone": "3",
    "_id": "54695f283d69cc501f7bdd89",
    "__v": 0
  },
  {
    "role": "sr-mgmt",
    "ivy": "true",
    "wr_style": "verbose",
    "industry": "finance",
    "risklevel": "8",
    "sentto": "team",
    "tone": "3",
    "_id": "54695f283d69cc501f7bdd8c",
    "__v": 0
  },
  {
    "tone": "3",
    "sentto": "team",
    "risklevel": "8",
    "industry": "technology",
    "wr_style": "concise",
    "ivy": "true",
    "role": "c_level",
    "_id": "546eb12859cb0ae4446f86fa",
    "__v": 0
  },
  {
    "tone": "3",
    "sentto": "team",
    "risklevel": "8",
    "industry": "healthcare",
    "wr_style": "concise",
    "ivy": "true",
    "role": "c_level",
    "_id": "5471d02a47031fec1891d850",
    "__v": 0
  },
  {
    "tone": "3",
    "sentto": "peer",
    "risklevel": "8",
    "industry": "finance",
    "wr_style": "concise",
    "ivy": "true",
    "role": "mid_mgmt",
    "_id": "5478d3c40c4db6ac1b7f654e",
    "__v": 0
  },
  {
    "tone": "3",
    "sentto": "peer",
    "risklevel": "8",
    "industry": "finance",
    "wr_style": "concise",
    "ivy": "true",
    "role": "mid_mgmt",
    "_id": "5478d43c0c4db6ac1b7f654f",
    "__v": 0
  },
  {
    "tone": "3",
    "sentto": "team",
    "risklevel": "8",
    "industry": "technology",
    "wr_style": "concise",
    "ivy": "true",
    "role": "mid_mgmt",
    "_id": "5478d4aaf9e699182d4391c2",
    "__v": 0
  },
  {
    "tone": "3",
    "sentto": "team",
    "risklevel": "8",
    "industry": "technology",
    "wr_style": "concise",
    "ivy": "true",
    "role": "mid_mgmt",
    "_id": "5478d522f9e699182d4391c3",
    "__v": 0
  },
  {
    "tone": "3",
    "sentto": "higher",
    "risklevel": "8",
    "industry": "retail",
    "wr_style": "verbose",
    "ivy": "false",
    "role": "mid_mgmt",
    "_id": "5478d728fa9a4df023250df0",
    "__v": 0
  },
  {
    "tone": "3",
    "sentto": "peer",
    "risklevel": "8",
    "industry": "airlines",
    "wr_style": "verbose",
    "ivy": "true",
    "role": "mid_mgmt",
    "_id": "5478d788fa9a4df023250df1",
    "__v": 0
  },
  {
    "tone": "3",
    "sentto": "peer",
    "risklevel": "8",
    "industry": "retail",
    "wr_style": "verbose",
    "ivy": "false",
    "role": "mid_mgmt",
    "_id": "5478d9080f5ed3482bccb3c3",
    "__v": 0
  },
  {
    "tone": "3",
    "sentto": "peer",
    "risklevel": "8",
    "industry": "airlines",
    "wr_style": "concise",
    "ivy": "true",
    "role": "mid_mgmt",
    "_id": "5478f206838aad5c29cb5853",
    "__v": 0
  },
  {
    "tone": "3",
    "sentto": "peer",
    "risklevel": "8",
    "industry": "retail",
    "wr_style": "concise",
    "ivy": "true",
    "role": "mid_mgmt",
    "_id": "5478f31b838aad5c29cb5854",
    "__v": 0
  },
  {
    "tone": "3",
    "sentto": "team",
    "risklevel": "8",
    "industry": "retail",
    "wr_style": "concise",
    "ivy": "true",
    "role": "c_level",
    "_id": "5483bb736d68a0242bcc6dde",
    "__v": 0
  },
  {
    "tone": "3",
    "sentto": "team",
    "risklevel": "8",
    "industry": "finance",
    "wr_style": "concise",
    "ivy": "true",
    "role": "c_level",
    "_id": "5483bea46d68a0242bcc6de5",
    "__v": 0
  },
  {
    "tone": "3",
    "sentto": "team",
    "risklevel": "8",
    "industry": "retail",
    "wr_style": "concise",
    "ivy": "true",
    "role": "c_level",
    "_id": "5483c1426d68a0242bcc6de6",
    "__v": 0
  },
  {
    "tone": "3",
    "sentto": "team",
    "risklevel": "8",
    "industry": "media",
    "wr_style": "concise",
    "ivy": "true",
    "role": "mid_mgmt",
    "_id": "5483c617e6cc38b4032f98a8",
    "__v": 0
  },
  {
    "tone": "3",
    "sentto": "team",
    "risklevel": "8",
    "industry": "media",
    "wr_style": "concise",
    "ivy": "true",
    "role": "c_level",
    "_id": "5483c770e6088d28031c79f8",
    "__v": 0
  },
  {
    "tone": "3",
    "sentto": "team",
    "risklevel": "8",
    "industry": "media",
    "wr_style": "concise",
    "ivy": "true",
    "role": "c_level",
    "_id": "5483c857e6088d28031c79fa",
    "__v": 0
  },
  {
    "tone": "3",
    "sentto": "team",
    "risklevel": "8",
    "industry": "media",
    "wr_style": "concise",
    "ivy": "true",
    "role": "c_level",
    "_id": "5483ca0be6088d28031c79fe",
    "__v": 0
  },
  {
    "tone": "3",
    "sentto": "team",
    "risklevel": "8",
    "industry": "media",
    "wr_style": "concise",
    "ivy": "true",
    "role": "mid_mgmt",
    "_id": "5483ce4be6088d28031c7a00",
    "__v": 0
  },
  {
    "tone": "3",
    "sentto": "team",
    "risklevel": "8",
    "industry": "media",
    "wr_style": "concise",
    "ivy": "true",
    "role": "c_level",
    "_id": "5483d06de6088d28031c7a03",
    "__v": 0
  },
  {
    "tone": "3",
    "sentto": "team",
    "risklevel": "8",
    "industry": "media",
    "wr_style": "concise",
    "ivy": "true",
    "role": "mid_mgmt",
    "_id": "5483d4276e7037b81ac2fdaa",
    "__v": 0
  },
  {
    "tone": "3",
    "sentto": "team",
    "risklevel": "8",
    "industry": "media",
    "wr_style": "concise",
    "ivy": "true",
    "role": "c_level",
    "_id": "5483d49e5b598178231543d6",
    "__v": 0
  },
  {
    "tone": "3",
    "sentto": "team",
    "risklevel": "8",
    "industry": "media",
    "wr_style": "concise",
    "ivy": "true",
    "role": "c_level",
    "_id": "5483d51b5b598178231543d8",
    "__v": 0
  },
  {
    "tone": "3",
    "sentto": "team",
    "risklevel": "8",
    "industry": "finance",
    "wr_style": "concise",
    "ivy": "true",
    "role": "c_level",
    "_id": "5483d5dc3b7a8ef428c05636",
    "__v": 0
  },
  {
    "tone": "3",
    "sentto": "team",
    "risklevel": "8",
    "industry": "finance",
    "wr_style": "concise",
    "ivy": "true",
    "role": "c_level",
    "_id": "5483d6313b7a8ef428c05638",
    "__v": 0
  },
  {
    "tone": "3",
    "sentto": "team",
    "risklevel": "8",
    "industry": "media",
    "wr_style": "concise",
    "ivy": "true",
    "role": "c_level",
    "_id": "5483d6653b7a8ef428c0563a",
    "__v": 0
  },
  {
    "tone": "3",
    "sentto": "team",
    "risklevel": "8",
    "industry": "media",
    "wr_style": "concise",
    "ivy": "true",
    "role": "c_level",
    "_id": "5483d7a93b7a8ef428c0563c",
    "__v": 0
  },
  {
    "tone": "3",
    "sentto": "team",
    "risklevel": "8",
    "industry": "finance",
    "wr_style": "concise",
    "ivy": "true",
    "role": "c_level",
    "_id": "5483d8933b7a8ef428c0563e",
    "__v": 0
  },
  {
    "tone": "3",
    "sentto": "peer",
    "risklevel": "8",
    "industry": "media",
    "wr_style": "concise",
    "ivy": "true",
    "role": "c_level",
    "_id": "548cd2efd8aba60822e9f609",
    "__v": 0
  },
  {
    "tone": "3",
    "sentto": "team",
    "risklevel": "8",
    "industry": "media",
    "wr_style": "concise",
    "ivy": "true",
    "role": "c_level",
    "_id": "548cd3add8aba60822e9f60b",
    "__v": 0
  },
  {
    "tone": "3",
    "sentto": "team",
    "risklevel": "8",
    "industry": "media",
    "wr_style": "concise",
    "ivy": "true",
    "role": "c_level",
    "_id": "548ce71ad8aba60822e9f60e",
    "__v": 0
  },
  {
    "tone": "3",
    "sentto": "team",
    "risklevel": "8",
    "industry": "media",
    "wr_style": "concise",
    "ivy": "true",
    "role": "c_level",
    "_id": "548cea0a56558e880f60f292",
    "__v": 0
  },
  {
    "tone": "3",
    "sentto": "team",
    "risklevel": "8",
    "industry": "finance",
    "wr_style": "verbose",
    "ivy": "false",
    "role": "vp",
    "_id": "5490e4513603a490243ca84a",
    "__v": 0
  },
  {
    "tone": "3",
    "sentto": "team",
    "risklevel": "8",
    "industry": "internet",
    "wr_style": "concise",
    "ivy": "true",
    "role": "c_level",
    "_id": "54a85a7edc5f319c22e9bd32",
    "__v": 0
  },
  {
    "tone": "3",
    "sentto": "higher",
    "risklevel": "8",
    "industry": "internet",
    "wr_style": "verbose",
    "ivy": "false",
    "role": "vp",
    "_id": "54bb05b6df1b6c901c83fac5",
    "__v": 0
  },
  {
    "_id": "549d99625c1dc8f801000003",
    "role": "sr-mgmt",
    "ivy": "true",
    "wr_style": "concise",
    "industry": "finance",
    "risklevel": "9",
    "sentto": "team",
    "tone": "3"
  },
  {
    "tone": "3",
    "sentto": "team",
    "risklevel": "9",
    "industry": "retail",
    "wr_style": "concise",
    "ivy": "true",
    "role": "sr_mgmt",
    "_id": "54af3810a2dcca782003f54a",
    "__v": 0
  },
  {
    "_id": "54695fd45c1dc8f004000002",
    "tone": "2",
    "sentto": "team",
    "risklevel": "2",
    "industry": "media",
    "wr_style": "concise",
    "ivy": "true",
    "role": "c_level"
  },
  {
    "tone": "2",
    "sentto": "peer",
    "risklevel": "2",
    "industry": "finance",
    "wr_style": "concise",
    "ivy": "true",
    "role": "c_level",
    "_id": "54695ffe3d69cc501f7bdd90",
    "__v": 0
  },
  {
    "role": "c_level",
    "ivy": "true",
    "wr_style": "concise",
    "industry": "finance",
    "risklevel": "5",
    "sentto": "higher",
    "tone": "2",
    "_id": "54695f283d69cc501f7bdd85",
    "__v": 0
  },
  {
    "tone": "2",
    "sentto": "team",
    "risklevel": "5",
    "industry": "media",
    "wr_style": "simple",
    "ivy": "true",
    "role": "c_level",
    "_id": "54695f473d69cc501f7bdd8f",
    "__v": 0
  },
  {
    "tone": "2",
    "sentto": "team",
    "risklevel": "5",
    "industry": "",
    "wr_style": "concise",
    "ivy": "true",
    "role": "c_level",
    "_id": "548dd1ac3603a490243ca83a",
    "__v": 0
  },
  {
    "tone": "2",
    "sentto": "team",
    "risklevel": "5",
    "industry": "retail",
    "wr_style": "simple",
    "ivy": "true",
    "role": "c_level",
    "_id": "549b549a2f009ba4287225f6",
    "__v": 0
  },
  {
    "tone": "2",
    "sentto": "team",
    "risklevel": "5",
    "industry": "education",
    "wr_style": "concise",
    "ivy": "true",
    "role": "c_level",
    "_id": "549b54e72f009ba4287225f8",
    "__v": 0
  },
  {
    "tone": "2",
    "sentto": "team",
    "risklevel": "5",
    "industry": "education",
    "wr_style": "concise",
    "ivy": "false",
    "role": "c_level",
    "_id": "549c4a8b127cfdac1f308337",
    "__v": 0
  },
  {
    "tone": "2",
    "sentto": "team",
    "risklevel": "5",
    "industry": "internet",
    "wr_style": "concise",
    "ivy": "true",
    "role": "c_level",
    "_id": "549cd656d66dedd42796895e",
    "__v": 0
  },
  {
    "role": "vp",
    "ivy": "false",
    "wr_style": "simple",
    "industry": "finance",
    "risklevel": "6",
    "sentto": "higher",
    "tone": "2",
    "_id": "54695f283d69cc501f7bdd84",
    "__v": 0
  },
  {
    "role": "c_level",
    "ivy": "true",
    "wr_style": "simple",
    "industry": "technology",
    "risklevel": "7",
    "sentto": "team",
    "tone": "2",
    "_id": "54695f283d69cc501f7bdd7c",
    "__v": 0
  },
  {
    "role": "c_level",
    "ivy": "true",
    "wr_style": "simple",
    "industry": "technology",
    "risklevel": "7",
    "sentto": "team",
    "tone": "2",
    "_id": "54695f283d69cc501f7bdd7e",
    "__v": 0
  },
  {
    "role": "c_level",
    "ivy": "true",
    "wr_style": "simple",
    "industry": "technology",
    "risklevel": "7",
    "sentto": "peer",
    "tone": "2",
    "_id": "54695f283d69cc501f7bdd81",
    "__v": 0
  },
  {
    "role": "c_level",
    "ivy": "true",
    "wr_style": "simple",
    "industry": "technology",
    "risklevel": "7",
    "sentto": "peer",
    "tone": "2",
    "_id": "54695f283d69cc501f7bdd86",
    "__v": 0
  },
  {
    "role": "mid_mgmt",
    "ivy": "false",
    "wr_style": "verbose",
    "industry": "technology",
    "risklevel": "7",
    "sentto": "team",
    "tone": "2",
    "_id": "54695f283d69cc501f7bdd88",
    "__v": 0
  },
  {
    "role": "c_level",
    "ivy": "true",
    "wr_style": "simple",
    "industry": "technology",
    "risklevel": "7",
    "sentto": "peer",
    "tone": "2",
    "_id": "54695f283d69cc501f7bdd8b",
    "__v": 0
  },
  {
    "tone": "2",
    "sentto": "peer",
    "risklevel": "7",
    "industry": "healthcare",
    "wr_style": "verbose",
    "ivy": "true",
    "role": "mid_mgmt",
    "_id": "546eac0ab97dd2b86b00c4cf",
    "__v": 0
  },
  {
    "tone": "2",
    "sentto": "higher",
    "risklevel": "7",
    "industry": "finance",
    "wr_style": "verbose",
    "ivy": "true",
    "role": "vp",
    "_id": "546eaef1a314e6b45afe7870",
    "__v": 0
  },
  {
    "tone": "2",
    "sentto": "peer",
    "risklevel": "7",
    "industry": "retail",
    "wr_style": "simple",
    "ivy": "true",
    "role": "c_level",
    "_id": "5478d0bc0f350cf01468383d",
    "__v": 0
  },
  {
    "tone": "2",
    "sentto": "peer",
    "risklevel": "7",
    "industry": "retail",
    "wr_style": "simple",
    "ivy": "true",
    "role": "c_level",
    "_id": "5478d611f9e699182d4391c5",
    "__v": 0
  },
  {
    "tone": "2",
    "sentto": "peer",
    "risklevel": "7",
    "industry": "retail",
    "wr_style": "verbose",
    "ivy": "false",
    "role": "mid_mgmt",
    "_id": "5478d6a71c8755202b6700cc",
    "__v": 0
  },
  {
    "tone": "2",
    "sentto": "peer",
    "risklevel": "7",
    "industry": "retail",
    "wr_style": "simple",
    "ivy": "true",
    "role": "mid_mgmt",
    "_id": "5478db8282cf21181d8424d1",
    "__v": 0
  },
  {
    "tone": "2",
    "sentto": "peer",
    "risklevel": "7",
    "industry": "retail",
    "wr_style": "simple",
    "ivy": "false",
    "role": "mid_mgmt",
    "_id": "5478dc0169a014a82c28d03f",
    "__v": 0
  },
  {
    "tone": "2",
    "sentto": "higher",
    "risklevel": "7",
    "industry": "airlines",
    "wr_style": "verbose",
    "ivy": "true",
    "role": "vp",
    "_id": "5478dcebaa9ba83c2930936e",
    "__v": 0
  },
  {
    "tone": "2",
    "sentto": "peer",
    "risklevel": "7",
    "industry": "airlines",
    "wr_style": "verbose",
    "ivy": "false",
    "role": "sr_mgmt",
    "_id": "5478ddb45dfbec080e3e68c2",
    "__v": 0
  },
  {
    "tone": "2",
    "sentto": "higher",
    "risklevel": "7",
    "industry": "ailrines",
    "wr_style": "simple",
    "ivy": "true",
    "role": "mid_mgmt",
    "_id": "5478ddfc6d331f9c26f814b2",
    "__v": 0
  },
  {
    "tone": "2",
    "sentto": "higher",
    "risklevel": "7",
    "industry": "retail",
    "wr_style": "verbose",
    "ivy": "true",
    "role": "mid_mgmt",
    "_id": "5478de5ade7c508c246deed8",
    "__v": 0
  },
  {
    "tone": "2",
    "sentto": "higher",
    "risklevel": "7",
    "industry": "retail",
    "wr_style": "simple",
    "ivy": "true",
    "role": "mid_mgmt",
    "_id": "5478debdde7c508c246deed9",
    "__v": 0
  },
  {
    "tone": "2",
    "sentto": "peer",
    "risklevel": "7",
    "industry": "finance",
    "wr_style": "simple",
    "ivy": "true",
    "role": "mid_mgmt",
    "_id": "5478e20cb5e542b41d5bdafe",
    "__v": 0
  },
  {
    "tone": "2",
    "sentto": "higher",
    "risklevel": "7",
    "industry": "media",
    "wr_style": "verbose",
    "ivy": "true",
    "role": "sr_mgmt",
    "_id": "548dd24a3603a490243ca840",
    "__v": 0
  },
  {
    "tone": "2",
    "sentto": "higher",
    "risklevel": "7",
    "industry": "finance",
    "wr_style": "simple",
    "ivy": "true",
    "role": "c_level",
    "_id": "5490e4c161e2b4482ae1b913",
    "__v": 0
  },
  {
    "tone": "2",
    "sentto": "higher",
    "risklevel": "7",
    "industry": "media",
    "wr_style": "verbose",
    "ivy": "false",
    "role": "vp",
    "_id": "5490e54f2f009ba4287225f4",
    "__v": 0
  },
  {
    "tone": "2",
    "sentto": "higher",
    "risklevel": "7",
    "industry": "retail",
    "wr_style": "verbose",
    "ivy": "false",
    "role": "vp",
    "_id": "54a8581ddc5f319c22e9bd30",
    "__v": 0
  },
  {
    "_id": "547125b15c1dc81019000001",
    "tone": "2",
    "sentto": "higher",
    "risklevel": "8",
    "industry": "finance",
    "wr_style": "simple",
    "ivy": "false",
    "role": "c_level"
  },
  {
    "tone": "2",
    "sentto": "higher",
    "risklevel": "8",
    "industry": "airlines",
    "wr_style": "simple",
    "ivy": "false",
    "role": "sr_mgmt",
    "_id": "5478dc4204ec975c22be2c55",
    "__v": 0
  },
  {
    "tone": "2",
    "sentto": "higher",
    "risklevel": "8",
    "industry": "airlines",
    "wr_style": "simple",
    "ivy": "false",
    "role": "mid_mgmt",
    "_id": "5478dd3eaa9ba83c29309370",
    "__v": 0
  },
  {
    "tone": "2",
    "sentto": "peer",
    "risklevel": "8",
    "industry": "airlines",
    "wr_style": "simple",
    "ivy": "true",
    "role": "sr_mgmt",
    "_id": "5478eaef1b221c4c23c773a7",
    "__v": 0
  },
  {
    "tone": "2",
    "sentto": "peer",
    "risklevel": "8",
    "industry": "airlines",
    "wr_style": "simple",
    "ivy": "true",
    "role": "mid_mgmt",
    "_id": "5478eeb487334f041b7d208a",
    "__v": 0
  },
  {
    "tone": "2",
    "sentto": "peer",
    "risklevel": "8",
    "industry": "finance",
    "wr_style": "simple",
    "ivy": "true",
    "role": "mid_mgmt",
    "_id": "5478eef787334f041b7d208b",
    "__v": 0
  },
  {
    "tone": "2",
    "sentto": "peer",
    "risklevel": "8",
    "industry": "airlines",
    "wr_style": "simple",
    "ivy": "true",
    "role": "c_level",
    "_id": "5478f4e22a533e501326e52b",
    "__v": 0
  },
  {
    "tone": "2",
    "sentto": "peer",
    "risklevel": "8",
    "industry": "finance",
    "wr_style": "simple",
    "ivy": "true",
    "role": "c_level",
    "_id": "54792e882a533e501326e52c",
    "__v": 0
  },
  {
    "tone": "2",
    "sentto": "peer",
    "risklevel": "8",
    "industry": "retail",
    "wr_style": "simple",
    "ivy": "true",
    "role": "mid_mgmt",
    "_id": "54a857d6dc5f319c22e9bd2e",
    "__v": 0
  },
  {
    "_id": "547125d75c1dc81019000002",
    "tone": "1",
    "sentto": "team",
    "risklevel": "1",
    "industry": "finance",
    "wr_style": "verbose",
    "ivy": "false",
    "role": "vp"
  },
  {
    "tone": "1",
    "sentto": "team",
    "risklevel": "1",
    "industry": "internet",
    "wr_style": "concise",
    "ivy": "false",
    "role": "c_level",
    "_id": "549dc72cafbbfa3c12528691",
    "__v": 0
  },
  {
    "_id": "54695fa05c1dc8f004000000",
    "tone": "1",
    "sentto": "team",
    "risklevel": "2",
    "industry": "media",
    "wr_style": "simple",
    "ivy": "true",
    "role": "c_level"
  },
  {
    "_id": "547125fe5c1dc81019000003",
    "tone": "1",
    "sentto": "higher",
    "risklevel": "2",
    "industry": "healthcare",
    "wr_style": "verbose",
    "ivy": "true",
    "role": "sr_mgmt"
  },
  {
    "role": "mid_mgmt",
    "ivy": "true",
    "wr_style": "concise",
    "industry": "healthcare",
    "risklevel": "3",
    "sentto": "team",
    "tone": "1",
    "_id": "54695f283d69cc501f7bdd8a",
    "__v": 0
  },
  {
    "role": "sr-mgmt",
    "ivy": "false",
    "wr_style": "verbose",
    "industry": "finance",
    "risklevel": "4",
    "sentto": "team",
    "tone": "1",
    "_id": "54695f283d69cc501f7bdd87",
    "__v": 0
  },
  {
    "tone": "1",
    "sentto": "peer",
    "risklevel": "4",
    "industry": "media",
    "wr_style": "simple",
    "ivy": "false",
    "role": "sr_mgmt",
    "_id": "547111eeda073db403ce927d",
    "__v": 0
  },
  {
    "tone": "1",
    "sentto": "peer",
    "risklevel": "4",
    "industry": "media",
    "wr_style": "simple",
    "ivy": "false",
    "role": "sr_mgmt",
    "_id": "54711277da073db403ce927e",
    "__v": 0
  },
  {
    "_id": "547125865c1dc81019000000",
    "tone": "1",
    "sentto": "higher",
    "risklevel": "4",
    "industry": "media",
    "wr_style": "simple",
    "ivy": "false",
    "role": "mid_mgmt"
  },
  {
    "tone": "1",
    "sentto": "team",
    "risklevel": "4",
    "industry": "internet",
    "wr_style": "concise",
    "ivy": "false",
    "role": "c_level",
    "_id": "54a20f7f8241e5582203b6b0",
    "__v": 0
  },
  {
    "role": "mid_mgmt",
    "ivy": "false",
    "wr_style": "simple",
    "industry": "healthcare",
    "risklevel": "5",
    "sentto": "peer",
    "tone": "1",
    "_id": "54695f283d69cc501f7bdd83",
    "__v": 0
  },
  {
    "role": "vp",
    "ivy": "false",
    "wr_style": "simple",
    "industry": "finance",
    "risklevel": "6",
    "sentto": "higher",
    "tone": "1",
    "_id": "54695f283d69cc501f7bdd8e",
    "__v": 0
  },
  {
    "0": {
      "role": "c-level",
      "ivy": "true",
      "wr_style": "concise",
      "industry": "finance",
      "risklevel": "10",
      "sentto": "team",
      "tone": "3"
    },
    "1": {
      "role": "sr-mgmt",
      "ivy": "true",
      "wr_style": "concise",
      "industry": "finance",
      "risklevel": "10",
      "sentto": "peer",
      "tone": "3"
    },
    "2": {
      "role": "c-level",
      "ivy": "true",
      "wr_style": "concise",
      "industry": "internet",
      "risklevel": "10",
      "sentto": "team",
      "tone": "3"
    },
    "_id": "549d990d5c1dc8f801000001"
  },
  {
    "0": {
      "role": "c-level",
      "ivy": "true",
      "wr_style": "concise",
      "industry": "finance",
      "risklevel": "9",
      "sentto": "team",
      "tone": "3"
    },
    "1": {
      "role": "sr-mgmt",
      "ivy": "true",
      "wr_style": "concise",
      "industry": "finance",
      "risklevel": "9",
      "sentto": "team",
      "tone": "3"
    },
    "2": {
      "role": "c-level",
      "ivy": "true",
      "wr_style": "concise",
      "industry": "finance",
      "risklevel": "10",
      "sentto": "team",
      "tone": "3"
    },
    "_id": "549d99455c1dc8f801000002"
  }
]